Home - MaximViewModel 설계하기
boostcampwm-2021/iOS10-JipJung pull request #111
Opened 2021-11-17 07:16 UTC by alibreo3754

# 작업 내용
- MaximViewModel을 ViewController와 연결시켰습니다.
- 좌로 넘길 수 있는 콜랙션 뷰를 만들었습니다.
- Dummy Data를 만지다보니, Realm을 실행할 때마다 초기화 하면 좋겠다 생각이 들어 관련된 로직을 추가하였습니다.
- image관련 로직은 url이 없다보니 일단 작성하지 않았고 위에 캘린더 버튼을 눌렀을 때 화면이 전환되는 로직부터 추가할까 합니다.
# 관련된 이슈 번호
- #110

# 스크린 샷(optional)
| 화면 제목을 적어주세요 |
|--|
| <img width="400" src="https://user-images.githubusercontent.com/40790219/142152604-abea7bc2-ee3b-4063-b66c-58fa22ecc1ad.gif"> |

2021-11-17 16:15 UTC, soohyeon0487 approved these changes
코드 확인했습니다. 코멘트 확인 부탁드립니다.

2021-11-17 16:15 UTC, soohyeon0487 commented on JipJung/JipJung/UI/Home/Maxim/ViewModels/MaximPresenterObject.swift
> +        let monthDict = ["JAN", "FEB", "MAR", "APR", "MAY", "JUN", "JUL", "AUG", "SEP", "OCT", "NOV", "DEC"]
배열인데 Dict을 적으면 밑의 코드에서 [index]를 [key]로 오인할 것 같습니다.
monthList 같은 변수명으로 바꾸는게 좋을 것 같습니다.

2021-11-17 16:15 UTC, soohyeon0487 commented on JipJung/JipJung/UI/Home/Maxim/ViewModels/MaximPresenterObject.swift
> +        let speaker = maxim.speaker == "" ? "미상" : maxim.speaker
isEmpty가 좀 더 깔끔할 것 같습니다.

2021-11-17 16:15 UTC, soohyeon0487 commented on JipJung/JipJung/UI/Home/Maxim/ViewModels/MaximViewModel.swift
> +    var maximLists: BehaviorRelay<[MaximPresenterObject]> { get }
maximList가 이미 복수의 뜻을 가지고 있는데 s가 또 붙은 maximLists는 어색한 것 같습니다.

2021-11-17 16:15 UTC, soohyeon0487 commented on JipJung/JipJung/UI/Home/Maxim/Views/MaximCollectionViewCell.swift
> +            $0.bottom.equalTo(self.safeAreaLayoutGuide.snp.bottom).offset(-20)
제 기억에는 self.safeAreaLayoutGuide.snp.bottom과 view.snp.bottomMargin이 같은 것으로 알고 있습니다.
다만 cell안에서도 똑같은 동작인지는 확신이 없네요 ㅎㅎ;;

2021-11-18 01:38 UTC, Kinaan-Oh approved these changes
확인하였습니다.

2021-11-18 01:38 UTC, Kinaan-Oh commented on JipJung/JipJung/UI/Home/Maxim/ViewModels/MaximPresenterObject.swift
> +        let monthDict = ["JAN", "FEB", "MAR", "APR", "MAY", "JUN", "JUL", "AUG", "SEP", "OCT", "NOV", "DEC"]
month를 enum으로 관리하는 것도 좋을것같습니다.

2021-11-18 01:40 UTC, jogiking approved these changes
확인했습니다. 수고하셨습니다.

2021-11-18 01:40 UTC, jogiking commented on JipJung/JipJung/Application/AppDelegate.swift
> +        #endif
개발을 위해 추가하신 부분 좋은 것 같습니다

2021-11-18 01:44 UTC, soohyeon0487 requested changes
수정 부탁드립니다.

2021-11-18 01:47 UTC, soohyeon0487 approved these changes

2021-11-18 02:05 UTC, merged