타이머 시작/정지와 배경의 오디오 콘텐츠 재생/정지 연동
boostcampwm-2021/iOS10-JipJung pull request #129
Opened 2021-11-22 08:25 UTC by soohyeon0487

# 작업 내용
- 타이머의 시작 정지와 음원 재생을 연동
- default와 infinite 모드만 적용
- 뽀모도로는 구현 후 추가
- breath는 별도 음원 필요

2021-11-22 08:40 UTC, Kinaan-Oh approved these changes
확인하였습니다.

2021-11-22 08:40 UTC, Kinaan-Oh commented on JipJung/JipJung/UI/Home/Main/Views/CarouselView.swift
> +        delegate.currentViewTapped()
좋은 방법인 것 같습니다.

2021-11-22 08:46 UTC, alibreo3754 reviewed
리뷰남겼습니다.

2021-11-22 08:46 UTC, alibreo3754 commented on JipJung/JipJung/Domain/UseCases/AudioPlayManager.swift
> +        isPlaying = autoPlay
readyToPlay가 노래를 틀 준비를 한다? 라는 뜻인가요 밑에 play()로직이 있어서 궁금합니다.

2021-11-22 08:46 UTC, alibreo3754 commented on JipJung/JipJung/UI/Home/Main/Views/CarouselView.swift
> +            .disposed(by: disposeBag)
Delegate는 어떤 action이 일어났고, 종료했다는 것을 알려주는 용도라 생각하는데 그 결과를 다시 가져와서 사용하는게 어색하지 않나 싶습니다. 참조관계로 따지면 이 객체는 하위 객체이기 때문에 상위 객체에서 바로 값을 주입시키는게 더 좋지않을까 하는 생각이 듭니다.

2021-11-22 08:50 UTC, soohyeon0487 commented on JipJung/JipJung/Domain/UseCases/AudioPlayManager.swift
> +        isPlaying = autoPlay
네 재생할 준비 정도라는 느낌입니다.

2021-11-22 09:03 UTC, jogiking requested changes
확인했습니다. 코멘트 확인부탁드립니다.

2021-11-22 09:03 UTC, jogiking commented on JipJung/JipJung/Domain/UseCases/AudioPlayManager.swift
> +    func controlAudio(state: Bool? = nil) -> Single<Bool> {
함수이름으로 무엇을 하는지 불명확한것 같습니다. state를 bool값이 아닌 따로 enum으로 이름을 지으면 좀 더 분명해질 것 같습니다.

2021-11-22 09:03 UTC, jogiking commented on JipJung/JipJung/Domain/UseCases/AudioPlayManager.swift
>      func isPlaying(of audioFileUrl: URL) -> Bool {
외부에서 잘못된 URL을 넣었을 때 현재 음악재생인지 반환하는지에 대해서 함수기능이 불명확한 것 같습니다. 그리고 프로퍼티와 동일한 이름의 함수는 지양하는 편이 좋은 것 같습니다

2021-11-22 09:03 UTC, soohyeon0487 commented on JipJung/JipJung/UI/Home/Main/Views/CarouselView.swift
> +            .disposed(by: disposeBag)
해당 부분 수정하였습니다. 확인 부탁드립니다!

2021-11-22 09:04 UTC, soohyeon0487 commented on JipJung/JipJung/Domain/UseCases/AudioPlayManager.swift
>      func isPlaying(of audioFileUrl: URL) -> Bool {
해당 부분은 제가 직접 사용하는 부분이 아니라 다른 분이 짠 곳에서 사용 중이라 빌드 유지를 위해 남겨두었습니다.
이에 대한 설명이 부족했던 점이 있으니 Todo나 FixMe를 통해 남겨두도록 하겠습니다.

2021-11-22 09:06 UTC, alibreo3754 approved these changes

2021-11-22 09:13 UTC, soohyeon0487 commented on JipJung/JipJung/Domain/UseCases/AudioPlayManager.swift
> +    func controlAudio(state: Bool? = nil) -> Single<Bool> {
해당 부분 수정했습니다. 코드 확인 부탁드립니다.

2021-11-23 01:03 UTC, jogiking approved these changes

2021-11-23 01:09 UTC, Kinaan-Oh approved these changes
확인하였습니다.

2021-11-23 01:10 UTC, alibreo3754 approved these changes

2021-11-23 01:19 UTC, merged