Feature/recent data
boostcampwm-2021/iOS10-JipJung pull request #147
Opened 2021-11-24 14:20 UTC by soohyeon0487

# 작업 내용
- PlayHistory 최신순으로 정렬
- PlayHistory 최대 노출 갯수 6개로 조절

2021-11-24 14:25 UTC, alibreo3754 approved these changes

2021-11-25 01:24 UTC, Kinaan-Oh approved these changes
확인하였습니다.

2021-11-25 01:36 UTC, alibreo3754 approved these changes

2021-11-25 01:36 UTC, jogiking requested changes
수고하셨습니다. 이번 변경사항에 맞게 포커스 음원재생 부분 수정이 필요할 것 같습니다.

2021-11-25 05:23 UTC, jogiking approved these changes

2021-11-25 05:25 UTC, merged