Feat/explore scene
boostcampwm-2021/iOS10-JipJung pull request #45
Opened 2021-11-05 14:51 UTC by Kinaan-Oh

# 작업 내용
- ExploreViewController, SearchViewController 구현

# 관련된 이슈 번호
close #31

2021-11-05 16:30 UTC, soohyeon0487 requested changes
코멘트 확인 부탁드립니다.

2021-11-05 16:30 UTC, soohyeon0487 commented on JipJung/JipJung/Application/SceneDelegate.swift
> +        let exploreViewController = UINavigationController(rootViewController: ExploreViewController())
NavigationController 관련 객체이므로 이름을 그대로 쓰기보단 Navigation임을 명시하는 변수명이 좋을 것 같습니다.

2021-11-05 16:30 UTC, soohyeon0487 commented on JipJung/JipJung/Application/SceneDelegate.swift
> +        exploreViewController.tabBarItem.image = UIImage(systemName: TabBarItems.Explore.image)
위의 createHomeViewController에서 tabBarItem을 설정하는 방식과 통일하는 것이 좋을 것 같습니다.

```swift
let tabBarItem = UITabBarItem(
    title: TabBarItems.Home.title,
    image: UIImage(systemName: TabBarItems.Home.image),
    tag: 0
)

let homeViewController = HomeViewController()
homeViewController.tabBarItem = tabBarItem
```

2021-11-05 16:30 UTC, soohyeon0487 commented on JipJung/JipJung/UI/Explore/Main/DummyCCell.swift
> +    static let cellIdentifier = "DummyCCell"
Swift Code Style 상, 축약어는 지양하는 것이 좋습니다.
DummyCollectionViewCell을 그대로 사용하시는게 어떨까요?

2021-11-05 16:30 UTC, soohyeon0487 commented on JipJung/JipJung/UI/Explore/Main/ExploreViewController.swift
> +                                forCellWithReuseIdentifier: DummyCCell.cellIdentifier)
개행의 방식이 파라미터끼리의 indent가 달라서 어색합니다.

Style Share Guide에서 처럼 파라미터 단위로 개행하는 것을 추천드립니다.

```swift
categoryCollectionView.register(
    DummyCCell.self, 
    forCellWithReuseIdentifier: DummyCCell.cellIdentifier
)
```

2021-11-05 16:30 UTC, soohyeon0487 commented on JipJung/JipJung/UI/Explore/Main/ExploreViewController.swift
> +
의미없는 개행처럼 보입니다.

2021-11-05 16:30 UTC, soohyeon0487 commented on JipJung/JipJung/UI/Explore/Main/ExploreViewController.swift
> +}
안쓰이는 Extension은 지워도 될 것 같습니다.

2021-11-05 16:30 UTC, soohyeon0487 commented on JipJung/JipJung/UI/Explore/Main/SearchTableViewCell.swift
> +        }
snapkit에서 left right 대신 leading trailing을 쓰신 부분은 의도하신 부분인가요?

2021-11-05 16:30 UTC, soohyeon0487 commented on JipJung/JipJung/UI/Explore/Main/SearchViewController.swift
> +        userDefaultStorage.save(for: "searchHistory", value: searchHistory)
rawString은 클래스 프로퍼티로 관리하는 것이 좋아보입니다.

2021-11-05 16:30 UTC, soohyeon0487 commented on JipJung/JipJung/UI/Explore/Main/SearchViewController.swift
> +        guard let keyword = searchBar.text  else { return }
text 뒤에 공백이 2칸입니다. 다른 곳과 통일해주세요.

2021-11-06 06:36 UTC, Kinaan-Oh commented on JipJung/JipJung/UI/Explore/Main/DummyCCell.swift
> +    static let cellIdentifier = "DummyCCell"
SwiftLint 코드길이 에러 때문에 임시적으로 축약어를 사용했습니다. 줄여쓸 수 있는 다른 좋은 표현으로 수정해보겠습니다.

2021-11-06 06:41 UTC, Kinaan-Oh commented on JipJung/JipJung/UI/Explore/Main/SearchTableViewCell.swift
> +        }
네. left, right 대신 leading, trailing을 사용하는 것이 권장된다고 리뷰어님께 피드백을 받은 경험이 있습니다.

2021-11-06 07:33 UTC, soohyeon0487 approved these changes
수정사항 확인하였습니다.

2021-11-07 06:19 UTC, alibreo3754 approved these changes
확인했습니다.

2021-11-07 11:15 UTC, jogiking approved these changes
확인했습니다. 궁금한 부분 코멘트 남겼습니다.

2021-11-07 11:15 UTC, jogiking commented on JipJung/JipJung/UI/Explore/Main/ExploreViewController.swift
> +    private lazy var categoryCollectionView: UICollectionView = {
반드시 사용하게 되는 UICollectionView에 lazy var 초기화를 하신 이유가 궁금합니다.

2021-11-08 05:18 UTC, Kinaan-Oh commented on JipJung/JipJung/UI/Explore/Main/ExploreViewController.swift
> +    private lazy var categoryCollectionView: UICollectionView = {
참고하시면 좋으실 것 같습니다.
https://velog.io/@dev-lena/View%EC%9D%98-lazy-%ED%94%84%EB%A1%9C%ED%8D%BC%ED%8B%B0

2021-11-08 05:41 UTC, merged