RecentMusicViewController, FavoriteMusicViewController 구현
boostcampwm-2021/iOS10-JipJung pull request #54
Opened 2021-11-08 09:33 UTC by Kinaan-Oh

# 작업 내용
- RecentMusicViewController, FavoriteMusicViewController  구현

# 관련된 이슈 번호
close #51

2021-11-08 14:53 UTC, soohyeon0487 requested changes
코드 확인했습니다.
코멘트 확인 부탁드립니다.

2021-11-08 14:53 UTC, soohyeon0487 commented on JipJung/JipJung/UI/Home/Main/FavoriteMusicViewController.swift
> +import UIKit
import를 중복으로 하셨습니다.

2021-11-08 14:53 UTC, soohyeon0487 commented on JipJung/JipJung/UI/Home/Main/FavoriteMusicViewController.swift
> +                                forCellWithReuseIdentifier: MusicCollectionViewCell.identifier)
코드가 길어서 개행할 경우, 일관성 있게 parameter마다 개행을 하는 것이 좋을 것 같습니다.
```swift
favoriteMusicCollectionView.register(
  MusicCollectionViewCell.self, 
  forCellWithReuseIdentifier: MusicCollectionViewCell.identifier
)
```

2021-11-08 14:53 UTC, soohyeon0487 commented on JipJung/JipJung/UI/Home/Main/RecentMusicViewController.swift
> +        guard let cell = collectionView.dequeueReusableCell(withReuseIdentifier: MusicCollectionViewCell.identifier, for: indexPath) as? MusicCollectionViewCell else { return  UICollectionViewCell()
너무 긴 코드인 것 같습니다. 해당 코드의 끝에 어떤 else 가 있는지 확인하기 위해 좌우스크롤이 필요한 상황은 피해야할 것 같습니다.

2021-11-08 15:23 UTC, Kinaan-Oh commented on JipJung/JipJung/UI/Home/Main/FavoriteMusicViewController.swift
> +import UIKit
부끄럽네요. 정정하겠습니다.

2021-11-09 00:52 UTC, jogiking approved these changes
확인했습니다

2021-11-09 02:08 UTC, Kinaan-Oh commented on JipJung/JipJung/UI/Home/Main/RecentMusicViewController.swift
> +        guard let cell = collectionView.dequeueReusableCell(withReuseIdentifier: MusicCollectionViewCell.identifier, for: indexPath) as? MusicCollectionViewCell else { return  UICollectionViewCell()
추후 해결방법을 찾게 되면 반영하겠습니다.

2021-11-09 02:14 UTC, soohyeon0487 approved these changes
수정사항 확인했습니다.

2021-11-09 02:32 UTC, merged