✨ MediaRepository 구현
boostcampwm-2021/iOS10-JipJung pull request #55
Opened 2021-11-08 14:50 UTC by jogiking

# 작업 내용
- 음원, 사진, 동영상을 가져오는 Repository 구현
- firebase에서 해당하는 파일을 가져옴
- 캐싱o (디바이스 캐싱)
- remote 부분을 주입 받는 방향으로 구현
- LocalFileManager.swift에 write 함수 추가함
  - RemoteService쪽에서 url이 바로 나와서 LocalFileManager의 write함수를 쓰기위해 별도로 data를 메모리에 올리지 않기 위함
 
# 관련된 이슈 번호
cloase #50 

# 사용 예시
```swift
import UIKit

import RxSwift
import SnapKit

class MeViewController: UIViewController {
    var bag = DisposeBag()
    var imageView = UIImageView()
    
    override func viewDidLoad() {
        super.viewDidLoad()
        view.backgroundColor = .cyan
        
        imageView.backgroundColor = .red
        
        let button = UIButton(type: .system)
        button.setTitle("start", for: .normal)
        button.addTarget(self, action: #selector(buttonTouched(_:)), for: .touchUpInside)
        view.addSubview(button)
        view.addSubview(imageView)
        button.snp.makeConstraints { make in
            make.center.equalToSuperview()
        }
        imageView.snp.makeConstraints { make in
            make.centerX.equalToSuperview()
            make.width.height.equalTo(200)
            make.bottom.equalTo(button.snp.top)
        }
    }
    
    @objc func buttonTouched(_ sender: UIButton) {
        let remoteServiceProvider: RemoteServiceAccessible = RemoteServiceProvider()
        let repository = MediaRepository(remoteServiceAccessible: remoteServiceProvider)
        let images = ["JipJung.png", "apple.png", "cherry.png", "grape.png"]
        let fileName = images.randomElement() ?? images[0]

        repository.fetch(fileName: fileName, type: .image).subscribe { event in
            switch event {
            case .failure(let error):
                print(error)
            case .success(let data):
                DispatchQueue.main.async {
                    self.imageView.image = UIImage(data: data)
                }
            }
        }.disposed(by: bag)
    }
}

```
- 버튼 클릭할 때 마다 랜덤한 사진을 띄워주는 코드(me화면)

2021-11-08 15:06 UTC, soohyeon0487 requested changes
코드 확인했습니다.
코멘트 확인 부탁드립니다.

2021-11-08 15:06 UTC, soohyeon0487 commented on JipJung/JipJung/Infra/File/LocalFileManager.swift
> +    func write(from: URL, fileName: String) -> Bool {
함수 헤더의 이름과 바디의 내용이 직관적으로 일치하지 않습니다.
차라리 move라는 함수를 별도로 만드는 것은 어떨까요?

2021-11-08 15:06 UTC, soohyeon0487 commented on JipJung/JipJung/Infra/File/LocalFileManager.swift
> +        let path = cachePath.appendingPathComponent(fileName, isDirectory: true)
isDirectory에 true를 주신 이유가 있을까요?

2021-11-08 15:06 UTC, soohyeon0487 commented on JipJung/JipJung/Infra/File/LocalFileManager.swift
> +            try FileManager.default.moveItem(at: from, to: path)
파라미터 이름으로 from을 쓰면 코드를 읽는 사람의 입장에서 파악하기가 어려울 것 같습니다.
아래처럼 역할에 따른 이름을 명확하도록 바꾸는게 좋을 것 같습니다.
```swift
func move(from url: URL, to fileName: String)
func move(_ url: URL, to fileName: String) // 영어 문장의 형태: Move A to B
```

2021-11-08 15:06 UTC, soohyeon0487 commented on JipJung/JipJung/Infra/Network/MediaRepository.swift
> +    case notsuchFile
s가 컨벤션에 어긋나도록 소문자로 되어있습니다.

2021-11-08 15:06 UTC, soohyeon0487 commented on JipJung/JipJung/Infra/Network/MediaRepository.swift
> +}
이전에 작성해주신 코드의 Error 네이밍 방식과 차이가 있는 것 같습니다.

```swift
enum RemoteServiceError: Error {
     case transportError
     case serverSideError
     case badURL
 }
```
~~ Error, ~~ Failed, failed~~ 중에서 하나의 방식으로 통일해야할 것 같습니다.

2021-11-08 16:02 UTC, Kinaan-Oh approved these changes
고생하셨습니다.

2021-11-08 16:02 UTC, hyunsik-0h commented on JipJung/JipJung/Infra/Network/MediaRepository.swift
> +
불필요한 공백으로 보입니다.

2021-11-09 02:00 UTC, jogiking commented on JipJung/JipJung/Infra/Network/MediaRepository.swift
> +
[Swift Style Guide-임포트](https://github.com/StyleShare/swift-style-guide#%EC%9E%84%ED%8F%AC%ED%8A%B8)에서 소개하는 규칙을 적용한 부분입니다. 다른분들과 조율이 필요할 것 같네요

2021-11-09 02:26 UTC, soohyeon0487 approved these changes
수정 확인했습니다.

2021-11-09 02:27 UTC, merged