DeafultFocusView Animation 구현하기
boostcampwm-2021/iOS10-JipJung pull request #69
Opened 2021-11-10 12:08 UTC by alibreo3754

# 작업 내용
- @Kinaan-Oh 님이 작업해주신 기본 Layout위에 Animation을 CustomAnimation으로 Pulse를 분리하였습니다.
- 현재 기본타이머의 뷰 부분만 건든 상태이고 뷰모델과 연동은 제대로 되어있지 않습니다.
- animationLayer 일시정지는 Extension으로 분리하였습니다.

# 관련된 이슈 번호
#57 - 기본타이머 만들기

# 스크린 샷(optional)
용량이 너무커서 올리지 못하였습니다. 슬랙에 공유해드리겠습니다.

2021-11-10 12:59 UTC, soohyeon0487 reviewed
코드 확인했습니다.
코멘트 확인 부탁드립니다.

2021-11-10 12:59 UTC, soohyeon0487 commented on JipJung/JipJung/UI/Common/BlurCircleButton.swift
> +    typealias Listner = () -> Void
Listener 오타일까요?

2021-11-10 12:59 UTC, soohyeon0487 commented on JipJung/JipJung/UI/Common/BlurCircleButton.swift
>      let iconBackground: UIView = {
밖에서 호출되지않는다면 private이 좋을 것 같습니다.

2021-11-10 12:59 UTC, soohyeon0487 commented on JipJung/JipJung/UI/Home/Focus/DefaultFocusTimerView.swift
> +    private let pulsesLayer = CALayer()
밑의 코드를 보니 개별적인 pulseLayer를 담아두는 Layer로 보입니다.
pulseLayer와 pulsesLayer는 자칫 실수하기 쉬우니 pulseGroupLayer 같은 이름으로 바꾸는 것은 어떨까요?

2021-11-10 12:59 UTC, soohyeon0487 commented on JipJung/JipJung/UI/Home/Focus/DefaultFocusViewController.swift
>          }
1과 4가 각각 무슨 뜻을 가진 숫자인지 바로 알기는 어려워보입니다.
class property로 상수를 선언하는게 어떨까요? (ex. maxPulseCount)

그리고 이부분은 코드의 취향차이인데 저는 가능하면 _ 사용을 줄이는 것이 코드 읽기에 도움이 된다고 생각하고 있습니다.
이처럼 반복문에서 index를 사용하지 않는 경우 forEach를 사용합니다.
```swift
(0..<maxPulseCount).forEach {
  // 로직
}
```

2021-11-10 12:59 UTC, soohyeon0487 commented on JipJung/JipJung/UI/Home/Main/HomeViewController.swift
> +        view.isUserInteractionEnabled = true
해당 부분 코드는 추가한 이유가 있을까요?
클론해서 주석처리 전후를 비교하니 딱히 차이점을 못찾았습니다.

2021-11-10 12:59 UTC, soohyeon0487 commented on JipJung/JipJung/UI/Home/Main/HomeViewController.swift
> +            }
클릭이벤트 핸들러를 따로 만드신 이유가 있을까요?

현재 Enum쪽에서 ViewController를 받아오는건 어색하게 보입니다.
의존성 주입 때문에 UseCase, Repository등을 ParentViewController에서 받아와야하기 때문에
차라리 따로 Factory Class를 만드는게 낫지않을까요?

2021-11-10 14:24 UTC, Kinaan-Oh commented on JipJung/JipJung/UI/Common/BlurCircleButton.swift
> +        print("hi")
출력문은 제거하는 것이 좋아보입니다.

2021-11-10 14:48 UTC, Kinaan-Oh requested changes
<확인한 오류>
- 디폴트 모드에서 Exit 버튼을 눌렀을 때 시간이 초기화 되지 않는다.
- 디폴트 모드에서 PickerView가 구현되어 있지 않습니다.
- 상진님의 작업이 제가 구현한 Infinity 모드에 영향을 미쳐 재대로 동작하지 않습니다.

2021-11-10 14:48 UTC, Kinaan-Oh commented on JipJung/JipJung/UI/Home/Focus/DefaultFocusViewController.swift
> +        print("hi")
출력문은 삭제해주는 것이 좋아보입니다.

2021-11-10 14:48 UTC, Kinaan-Oh commented on JipJung/JipJung/UI/Home/Focus/Enums.swift
> +            return FocusViewController.Factory.makeInfinityTimer()
뷰 컨트롤러 팩토리는 합의되지 않은 사항으로 보입니다. 추후 함께 논의 후 채택해야할 부분으로 생각됩니다.

2021-11-10 14:48 UTC, Kinaan-Oh commented on JipJung/JipJung/UI/Home/Focus/FocusViewController.swift
> +    enum Factory {
뷰 컨트롤러 팩토리는 합의되지 않은 사항입니다. 제가 작업한 InfinityFocusViewController과 연관되므로 추후 논의할 사항으로 보입니다.

2021-11-10 14:48 UTC, Kinaan-Oh commented on JipJung/JipJung/UI/Home/Focus/DefaultFocusStartView.swift
> +class DefaultFocusStartView: UIView, FocusStartViewable {
금일 멘토님께서 말씀하신 것처럼 4개의 뷰컨트롤러를 사용하는 방법이 더 적절하다고 판단하고 이 방법을 사용할 것으로 금일 저녁 합의 된 것으로 이해했습니다. 사용하지 않을 파일을 포함한 이유가 있을까요?

2021-11-10 14:48 UTC, Kinaan-Oh commented on JipJung/JipJung/UI/Animation/CALayer+Extension.swift
> +    func pauseLayer() {
레이어의 재사용성을 높여주는 방법 배워갑니다.

2021-11-11 02:29 UTC, alibreo3754 commented on JipJung/JipJung/UI/Common/BlurCircleButton.swift
>      let iconBackground: UIView = {
외부에서 Listener를 주입해줘야하기때분에 internal로 공개되었습니다.

2021-11-11 02:30 UTC, alibreo3754 commented on JipJung/JipJung/UI/Home/Focus/DefaultFocusViewController.swift
>          }
forEach를 사용하더라도 클로저내부에서 _ in을 사용하기때문에 굳이 그럴필욘없을 것 같습니다. 리터럴은 수정하겠습니다.

2021-11-11 02:31 UTC, alibreo3754 commented on JipJung/JipJung/UI/Home/Main/HomeViewController.swift
> +            }
리스너를 주입해 버튼이 동작을 알아서 처리하도록 만드는게 낫다생각해서 그렇게 구현했습니다.

2021-11-11 02:31 UTC, alibreo3754 commented on JipJung/JipJung/UI/Home/Focus/DefaultFocusStartView.swift
> +class DefaultFocusStartView: UIView, FocusStartViewable {
리뷰 후 삭제할 예정입니다.

2021-11-11 04:47 UTC, soohyeon0487 commented on JipJung/JipJung/UI/Common/BlurCircleButton.swift
>      let iconBackground: UIView = {
16라인의 iconBackground를 찍어서 코멘트를 달았는데 코드 상으로는 저렇게 나오네요 ㅠ

2021-11-11 06:21 UTC, soohyeon0487 approved these changes

2021-11-11 06:26 UTC, jogiking approved these changes

2021-11-11 09:05 UTC, merged